import { Document, Font, Page, StyleSheet, Text, View, pdf } from '@react-pdf/renderer'
import type { Lang } from '@/i18n'
import { dateTime, shortDate } from '@/lib/format'
import type { Garage, ServiceRequest } from '@/types/domain'
import type { ServiceRequestAttachment } from '@/features/attachments/model'
import type { DeliveryReport } from './model'

const ARABIC_PDF_FONT = 'Amiri'

Font.register({
  family: ARABIC_PDF_FONT,
  fonts: [
    { src: '/fonts/Amiri-Regular.ttf', fontWeight: 400 },
    { src: '/fonts/Amiri-Bold.ttf', fontWeight: 700 },
  ],
})

const labels = {
  fr: {
    title: 'Rapport de restitution', client: 'Client', vehicle: 'Véhicule', dates: 'Dates',
    checkIn: 'Dépôt', delivered: 'Restitution', mileage: 'Kilométrage', entry: 'Entrée', exit: 'Sortie',
    requested: 'Travaux demandés', diagnosis: 'Diagnostic', completed: 'Prestations réalisées',
    accepted: 'Recommandations acceptées', deferred: 'Recommandations refusées ou reportées',
    parts: 'Pièces', observations: 'Observations', next: 'Prochaine échéance', warranty: 'Garantie',
    validation: 'Validation finale', noValue: 'Non renseigné', km: 'km',
    attachments: 'Photos et documents autorisés',
    legal: 'Document généré par Clikarage, un service édité par RODANBTECH.',
  },
  en: {
    title: 'Vehicle handover report', client: 'Customer', vehicle: 'Vehicle', dates: 'Dates',
    checkIn: 'Check-in', delivered: 'Handover', mileage: 'Mileage', entry: 'Entry', exit: 'Exit',
    requested: 'Requested work', diagnosis: 'Diagnosis', completed: 'Completed work',
    accepted: 'Accepted recommendations', deferred: 'Declined or deferred recommendations',
    parts: 'Parts', observations: 'Observations', next: 'Next service due', warranty: 'Warranty',
    validation: 'Final validation', noValue: 'Not provided', km: 'km',
    attachments: 'Authorized photos and documents',
    legal: 'Document generated by Clikarage, a service published by RODANBTECH.',
  },
  ar: {
    title: 'تقرير تسليم السيارة', client: 'العميل', vehicle: 'السيارة', dates: 'التواريخ',
    checkIn: 'الاستلام', delivered: 'التسليم', mileage: 'المسافة المقطوعة', entry: 'عند الدخول', exit: 'عند الخروج',
    requested: 'الأعمال المطلوبة', diagnosis: 'التشخيص', completed: 'الأعمال المنجزة',
    accepted: 'التوصيات المقبولة', deferred: 'التوصيات المرفوضة أو المؤجلة',
    parts: 'قطع الغيار', observations: 'ملاحظات', next: 'موعد الصيانة القادم', warranty: 'الضمان',
    validation: 'التحقق النهائي', noValue: 'غير محدد', km: 'كم',
    attachments: 'الصور والمستندات المصرح بها',
    legal: 'تم إنشاء المستند بواسطة Clikarage، وهي خدمة تقدمها RODANBTECH.',
  },
} satisfies Record<Lang, Record<string, string>>

export function deliveryReportLabels(lang: Lang) {
  return labels[lang]
}

function snapshotText(snapshot: Record<string, unknown>, keys: string[], fallback: string) {
  for (const key of keys) {
    const value = snapshot[key]
    if (typeof value === 'string' && value.trim()) return value
  }
  return fallback
}

function reportStyles(rtl: boolean, accent: string) {
  const bold = rtl
    ? { fontFamily: ARABIC_PDF_FONT, fontWeight: 700 as const }
    : { fontFamily: 'Helvetica-Bold' }
  return StyleSheet.create({
    page: { padding: 38, color: '#1e293b', fontSize: 9, fontFamily: rtl ? ARABIC_PDF_FONT : 'Helvetica' },
    header: { flexDirection: rtl ? 'row-reverse' : 'row', justifyContent: 'space-between', borderBottomWidth: 2, borderBottomColor: accent, paddingBottom: 12 },
    garage: { fontSize: 14, color: '#0f172a', textAlign: rtl ? 'right' : 'left', ...bold },
    title: { fontSize: 17, color: accent, textAlign: rtl ? 'left' : 'right', ...bold },
    meta: { color: '#64748b', textAlign: rtl ? 'left' : 'right' },
    grid: { flexDirection: rtl ? 'row-reverse' : 'row', gap: 12, marginTop: 14 },
    half: { width: '50%' },
    label: { color: '#64748b', fontSize: 8, marginBottom: 3, textAlign: rtl ? 'right' : 'left', ...bold },
    value: { color: '#0f172a', textAlign: rtl ? 'right' : 'left' },
    section: { marginTop: 13, paddingTop: 8, borderTopWidth: 1, borderTopColor: '#e2e8f0' },
    listItem: { marginTop: 2, textAlign: rtl ? 'right' : 'left' },
    footer: { position: 'absolute', bottom: 18, left: 38, right: 38, color: '#94a3b8', fontSize: 7, textAlign: 'center' },
  })
}

export interface DeliveryReportPdfData {
  report: DeliveryReport
  request: ServiceRequest
  garage: Garage | null
  lang: Lang
  attachments?: ServiceRequestAttachment[]
}

function renderReportSection({ title, values, fallback, styles }: {
  title: string
  values: Array<string | null | undefined>
  fallback: string
  styles: ReturnType<typeof reportStyles>
}) {
  const visible = values.filter((value): value is string => !!value?.trim())
  return (
    <View style={styles.section} wrap={false}>
      <Text style={styles.label}>{title}</Text>
      {visible.length ? visible.map((value, index) => <Text key={`${title}-${index}`} style={styles.listItem}>• {value}</Text>) : <Text style={styles.value}>{fallback}</Text>}
    </View>
  )
}

function deliveryReportDocument({ report, request, garage, lang, attachments = [] }: DeliveryReportPdfData) {
  const text = labels[lang]
  const rtl = lang === 'ar'
  const styles = reportStyles(rtl, garage?.accent_color || '#0f766e')
  const customer = snapshotText(report.customer_snapshot, ['name', 'full_name'], text.noValue)
  const vehicle = snapshotText(report.vehicle_snapshot, ['label', 'vehicle_label'], request.vehicle_label || text.noValue)
  return (
    <Document title={`${text.title} ${report.report_number}`}>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <View>
            <Text style={styles.garage}>{garage?.name ?? 'Clikarage'}</Text>
            <Text style={styles.value}>{garage?.address ?? ''}</Text>
            <Text style={styles.value}>{[garage?.phone, garage?.email].filter(Boolean).join(' · ')}</Text>
          </View>
          <View>
            <Text style={styles.title}>{text.title}</Text>
            <Text style={styles.meta}>{report.report_number}</Text>
            <Text style={styles.meta}>{shortDate(report.finalized_at ?? report.updated_at, lang)}</Text>
          </View>
        </View>

        <View style={styles.grid}>
          <View style={styles.half}><Text style={styles.label}>{text.client}</Text><Text style={styles.value}>{customer}</Text></View>
          <View style={styles.half}><Text style={styles.label}>{text.vehicle}</Text><Text style={styles.value}>{vehicle}</Text></View>
        </View>
        <View style={styles.grid}>
          <View style={styles.half}>
            <Text style={styles.label}>{text.dates}</Text>
            <Text style={styles.value}>{text.checkIn}: {report.checked_in_at ? dateTime(report.checked_in_at, lang) : text.noValue}</Text>
            <Text style={styles.value}>{text.delivered}: {report.delivered_at ? dateTime(report.delivered_at, lang) : text.noValue}</Text>
          </View>
          <View style={styles.half}>
            <Text style={styles.label}>{text.mileage}</Text>
            <Text style={styles.value}>{text.entry}: {report.entry_mileage ?? text.noValue} {report.entry_mileage !== null ? text.km : ''}</Text>
            <Text style={styles.value}>{text.exit}: {report.exit_mileage ?? text.noValue} {report.exit_mileage !== null ? text.km : ''}</Text>
          </View>
        </View>

        {renderReportSection({ title: text.requested, values: report.requested_work, fallback: text.noValue, styles })}
        {renderReportSection({ title: text.diagnosis, values: [report.diagnostic_summary], fallback: text.noValue, styles })}
        {renderReportSection({ title: text.completed, values: report.completed_work, fallback: text.noValue, styles })}
        {renderReportSection({ title: text.accepted, values: report.accepted_recommendations, fallback: text.noValue, styles })}
        {renderReportSection({ title: text.deferred, values: report.deferred_recommendations, fallback: text.noValue, styles })}
        {renderReportSection({ title: text.parts, values: report.parts, fallback: text.noValue, styles })}
        {renderReportSection({
          title: text.attachments,
          values: attachments.filter((item) => report.authorized_attachment_ids.includes(item.id)).map((item) => item.file_name),
          fallback: text.noValue,
          styles,
        })}
        {renderReportSection({ title: text.observations, values: [report.observations], fallback: text.noValue, styles })}
        {renderReportSection({ title: text.next, values: [
          report.next_due_date ? shortDate(report.next_due_date, lang) : null,
          report.next_due_mileage !== null ? `${report.next_due_mileage} ${text.km}` : null,
        ], fallback: text.noValue, styles })}
        {renderReportSection({ title: text.warranty, values: [report.warranty_terms], fallback: text.noValue, styles })}
        {renderReportSection({ title: text.validation, values: [report.final_validation], fallback: text.noValue, styles })}
        <Text fixed style={styles.footer}>{text.legal}</Text>
      </Page>
    </Document>
  )
}

export async function downloadDeliveryReportPdf(data: DeliveryReportPdfData) {
  const blob = await pdf(deliveryReportDocument(data)).toBlob()
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = `${data.report.report_number}.pdf`
  document.body.appendChild(anchor)
  anchor.click()
  anchor.remove()
  setTimeout(() => URL.revokeObjectURL(url), 2000)
}
