import { Document, Font, Image, Page, StyleSheet, Text, View, pdf } from '@react-pdf/renderer'
import type { Lang } from '@/i18n'
import { dateTime, shortDate } from '@/lib/format'
import type { Garage, ServiceRequest } from '@/types/domain'
import type { ServiceRequestAttachment } from '@/features/attachments/model'
import type { DeliveryReport } from './model'

const ARABIC_PDF_FONT = 'Amiri'

function publicAssetPath(path: string) {
  if (typeof window !== 'undefined') return path
  const localPath = decodeURIComponent(new URL(`../../../public${path}`, import.meta.url).pathname)
  return localPath.replace(/^\/([A-Za-z]:\/)/, '$1')
}

Font.register({
  family: ARABIC_PDF_FONT,
  fonts: [
    { src: publicAssetPath('/fonts/Amiri-Regular.ttf'), fontWeight: 400 },
    { src: publicAssetPath('/fonts/Amiri-Bold.ttf'), fontWeight: 700 },
  ],
})

const labels = {
  fr: {
    title: 'Rapport de restitution', client: 'Client', vehicle: 'Véhicule', dates: 'Dates',
    checkIn: 'Dépôt', delivered: 'Restitution', mileage: 'Kilométrage', entry: 'Entrée', exit: 'Sortie',
    requested: 'Travaux demandés', diagnosis: 'Diagnostic', completed: 'Prestations réalisées',
    accepted: 'Recommandations acceptées', deferred: 'Recommandations refusées ou reportées',
    parts: 'Pièces', observations: 'Observations', next: 'Prochaine échéance', warranty: 'Garantie',
    validation: 'Validation finale', noValue: 'Non renseigné', km: 'km',
    attachments: 'Photos et documents autorisés', center: 'Établissement', amounts: 'Synthèse financière', page: 'Page', photo: 'Photo',
    legal: 'Document généré par Clikarage, un service édité par RODANBTECH.',
  },
  en: {
    title: 'Vehicle handover report', client: 'Customer', vehicle: 'Vehicle', dates: 'Dates',
    checkIn: 'Check-in', delivered: 'Handover', mileage: 'Mileage', entry: 'Entry', exit: 'Exit',
    requested: 'Requested work', diagnosis: 'Diagnosis', completed: 'Completed work',
    accepted: 'Accepted recommendations', deferred: 'Declined or deferred recommendations',
    parts: 'Parts', observations: 'Observations', next: 'Next service due', warranty: 'Warranty',
    validation: 'Final validation', noValue: 'Not provided', km: 'km',
    attachments: 'Authorized photos and documents', center: 'Service center', amounts: 'Financial summary', page: 'Page', photo: 'Photo',
    legal: 'Document generated by Clikarage, a service published by RODANBTECH.',
  },
  ar: {
    title: 'تقرير تسليم السيارة', client: 'العميل', vehicle: 'السيارة', dates: 'التواريخ',
    checkIn: 'الاستلام', delivered: 'التسليم', mileage: 'المسافة المقطوعة', entry: 'عند الدخول', exit: 'عند الخروج',
    requested: 'الأعمال المطلوبة', diagnosis: 'التشخيص', completed: 'الأعمال المنجزة',
    accepted: 'التوصيات المقبولة', deferred: 'التوصيات المرفوضة أو المؤجلة',
    parts: 'قطع الغيار', observations: 'ملاحظات', next: 'موعد الصيانة القادم', warranty: 'الضمان',
    validation: 'التحقق النهائي', noValue: 'غير محدد', km: 'كم',
    attachments: 'الصور والمستندات المصرح بها', center: 'المركز', amounts: 'الملخص المالي', page: 'الصفحة', photo: 'صورة',
    legal: 'تم إنشاء المستند بواسطة Clikarage، وهي خدمة تقدمها RODANBTECH.',
  },
} satisfies Record<Lang, Record<string, string>>

export function deliveryReportLabels(lang: Lang) {
  return labels[lang]
}

function snapshotText(snapshot: Record<string, unknown>, keys: string[], fallback: string) {
  for (const key of keys) {
    const value = snapshot[key]
    if (typeof value === 'string' && value.trim()) return value
  }
  return fallback
}

function reportStyles(rtl: boolean, accent: string) {
  const bold = rtl
    ? { fontFamily: ARABIC_PDF_FONT, fontWeight: 700 as const }
    : { fontFamily: 'Helvetica-Bold' }
  return StyleSheet.create({
    page: { paddingTop: 38, paddingHorizontal: 38, paddingBottom: 48, color: '#1e293b', fontSize: 9, fontFamily: rtl ? ARABIC_PDF_FONT : 'Helvetica' },
    header: { flexDirection: rtl ? 'row-reverse' : 'row', justifyContent: 'space-between', borderBottomWidth: 2, borderBottomColor: accent, paddingBottom: 12 },
    garage: { fontSize: 14, color: '#0f172a', textAlign: rtl ? 'right' : 'left', ...bold },
    title: { fontSize: 17, color: accent, textAlign: rtl ? 'left' : 'right', ...bold },
    meta: { color: '#64748b', textAlign: rtl ? 'left' : 'right' },
    grid: { flexDirection: rtl ? 'row-reverse' : 'row', gap: 12, marginTop: 14 },
    half: { width: '50%' },
    label: { color: '#64748b', fontSize: 8, marginBottom: 3, textAlign: rtl ? 'right' : 'left', ...bold },
    value: { color: '#0f172a', textAlign: rtl ? 'right' : 'left' },
    technical: { color: '#0f172a', direction: 'ltr' as const, fontFamily: 'Helvetica', textAlign: 'left' as const },
    factRow: { flexDirection: rtl ? 'row-reverse' : 'row', justifyContent: 'space-between', gap: 8, marginTop: 2 },
    factLabel: { color: '#475569', textAlign: rtl ? 'right' : 'left', flexGrow: 1 },
    dateValue: { color: '#0f172a', direction: rtl ? 'rtl' as const : 'ltr' as const, textAlign: rtl ? 'left' : 'right', flexGrow: 1 },
    section: { marginTop: 13, paddingTop: 8, borderTopWidth: 1, borderTopColor: '#e2e8f0' },
    listRow: { flexDirection: rtl ? 'row-reverse' : 'row', gap: 5, marginTop: 2 },
    listBullet: { width: 8, textAlign: 'center' },
    listItem: { width: '96%', textAlign: rtl ? 'right' : 'left' },
    attachmentGrid: { flexDirection: rtl ? 'row-reverse' : 'row', flexWrap: 'wrap', gap: 8, marginTop: 6 },
    attachmentCard: { width: '48%', borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 4, overflow: 'hidden' },
    attachmentImage: { width: '100%', height: 86, objectFit: 'cover' as const },
    attachmentPlaceholder: { height: 86, alignItems: 'center', justifyContent: 'center', backgroundColor: '#e2e8f0', color: '#64748b' },
    attachmentName: { padding: 5, direction: 'ltr' as const, fontFamily: 'Helvetica', fontSize: 7, textAlign: 'left' as const },
    footer: { position: 'absolute', bottom: 18, left: 38, right: 38, color: '#94a3b8', fontSize: 7, textAlign: 'center' },
  })
}

export interface DeliveryReportPdfData {
  report: DeliveryReport
  request: ServiceRequest
  garage: Garage | null
  lang: Lang
  attachments?: ServiceRequestAttachment[]
  centerName?: string | null
  financialSummary?: string[]
  attachmentPreviews?: Record<string, string>
}

function renderReportSection({ title, values, fallback, styles }: {
  title: string
  values: Array<string | null | undefined>
  fallback: string
  styles: ReturnType<typeof reportStyles>
}) {
  const visible = values.filter((value): value is string => !!value?.trim())
  return (
    <View style={styles.section} minPresenceAhead={24}>
      <Text style={styles.label}>{title}</Text>
      {visible.length ? visible.map((value, index) => (
        <View key={`${title}-${index}`} style={styles.listRow}>
          <Text style={styles.listBullet}>•</Text>
          <Text style={styles.listItem}>{value}</Text>
        </View>
      )) : <Text style={styles.value}>{fallback}</Text>}
    </View>
  )
}

function renderFactRow({ label, value, technical, styles }: {
  label: string
  value: string
  technical?: boolean
  styles: ReturnType<typeof reportStyles>
}) {
  return (
    <View style={styles.factRow}>
      <Text style={styles.factLabel}>{label}</Text>
      <Text style={technical ? styles.technical : styles.dateValue}>{value}</Text>
    </View>
  )
}

function renderTechnicalSection({ title, values, fallback, styles }: {
  title: string
  values: string[]
  fallback: string
  styles: ReturnType<typeof reportStyles>
}) {
  return (
    <View style={styles.section} wrap={false}>
      <Text style={styles.label}>{title}</Text>
      {values.length
        ? values.map((value) => <Text key={value} style={styles.technical}>{value}</Text>)
        : <Text style={styles.value}>{fallback}</Text>}
    </View>
  )
}

export function deliveryReportDocument({
  report,
  request,
  garage,
  lang,
  attachments = [],
  centerName,
  financialSummary = [],
  attachmentPreviews = {},
}: DeliveryReportPdfData) {
  const text = labels[lang]
  const rtl = lang === 'ar'
  const styles = reportStyles(rtl, garage?.accent_color || '#0f766e')
  const customer = snapshotText(report.customer_snapshot, ['name', 'full_name'], text.noValue)
  const vehicle = snapshotText(report.vehicle_snapshot, ['label', 'vehicle_label'], request.vehicle_label || text.noValue)
  const registration = snapshotText(report.vehicle_snapshot, ['registration', 'plate'], '')
  const authorizedAttachments = attachments.filter((item) => report.authorized_attachment_ids.includes(item.id))
  const numberFormat = new Intl.NumberFormat(lang === 'fr' ? 'fr-FR' : lang === 'ar' ? 'ar-MA' : 'en-GB')
  const localizedDate = (value: string) => rtl ? `\u200F${value}\u200F` : value
  return (
    <Document title={`${text.title} ${report.report_number}`}>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <View>
            <Text style={styles.garage}>{garage?.name ?? 'Clikarage'}</Text>
            <Text style={styles.value}>{garage?.address ?? ''}</Text>
            <Text style={styles.technical}>{[garage?.phone, garage?.email].filter(Boolean).join(' · ')}</Text>
          </View>
          <View>
            <Text style={styles.title}>{text.title}</Text>
            <Text style={styles.technical}>{report.report_number}</Text>
            <Text style={styles.dateValue}>{localizedDate(shortDate(report.finalized_at ?? report.updated_at, lang))}</Text>
          </View>
        </View>

        {centerName && (
          <View style={styles.section}>
            <Text style={styles.label}>{text.center}</Text>
            <Text style={styles.value}>{centerName}</Text>
          </View>
        )}

        <View style={styles.grid}>
          <View style={styles.half}><Text style={styles.label}>{text.client}</Text><Text style={styles.value}>{customer}</Text></View>
          <View style={styles.half}>
            <Text style={styles.label}>{text.vehicle}</Text>
            <Text style={styles.value}>{vehicle}</Text>
            {registration && <Text style={styles.technical}>{registration}</Text>}
          </View>
        </View>
        <View style={styles.grid}>
          <View style={styles.half}>
            <Text style={styles.label}>{text.dates}</Text>
            {renderFactRow({ label: text.checkIn, value: report.checked_in_at ? localizedDate(dateTime(report.checked_in_at, lang)) : text.noValue, styles })}
            {renderFactRow({ label: text.delivered, value: report.delivered_at ? localizedDate(dateTime(report.delivered_at, lang)) : text.noValue, styles })}
          </View>
          <View style={styles.half}>
            <Text style={styles.label}>{text.mileage}</Text>
            {renderFactRow({
              label: text.entry,
              value: report.entry_mileage === null ? text.noValue : `${numberFormat.format(report.entry_mileage)} km`,
              technical: report.entry_mileage !== null,
              styles,
            })}
            {renderFactRow({
              label: text.exit,
              value: report.exit_mileage === null ? text.noValue : `${numberFormat.format(report.exit_mileage)} km`,
              technical: report.exit_mileage !== null,
              styles,
            })}
          </View>
        </View>

        {renderReportSection({ title: text.requested, values: report.requested_work, fallback: text.noValue, styles })}
        {renderReportSection({ title: text.diagnosis, values: [report.diagnostic_summary], fallback: text.noValue, styles })}
        {renderReportSection({ title: text.completed, values: report.completed_work, fallback: text.noValue, styles })}
        {renderReportSection({ title: text.accepted, values: report.accepted_recommendations, fallback: text.noValue, styles })}
        {renderReportSection({ title: text.deferred, values: report.deferred_recommendations, fallback: text.noValue, styles })}
        {renderReportSection({ title: text.parts, values: report.parts, fallback: text.noValue, styles })}
        {renderTechnicalSection({ title: text.amounts, values: financialSummary, fallback: text.noValue, styles })}
        <View style={styles.section} minPresenceAhead={110}>
          <Text style={styles.label}>{text.attachments}</Text>
          {authorizedAttachments.length ? (
            <View style={styles.attachmentGrid}>
              {authorizedAttachments.map((item) => (
                <View key={item.id} style={styles.attachmentCard} wrap={false}>
                  {attachmentPreviews[item.id]
                    ? <Image src={attachmentPreviews[item.id]} style={styles.attachmentImage} />
                    : <View style={styles.attachmentPlaceholder}><Text>{text.photo}</Text></View>}
                  <Text style={styles.attachmentName}>{item.file_name}</Text>
                </View>
              ))}
            </View>
          ) : <Text style={styles.value}>{text.noValue}</Text>}
        </View>
        {renderReportSection({ title: text.observations, values: [report.observations], fallback: text.noValue, styles })}
        <View style={styles.section} minPresenceAhead={24}>
          <Text style={styles.label}>{text.next}</Text>
          {report.next_due_date && <Text style={styles.value}>{localizedDate(shortDate(report.next_due_date, lang))}</Text>}
          {report.next_due_mileage !== null && <Text style={styles.technical}>{numberFormat.format(report.next_due_mileage)} km</Text>}
          {!report.next_due_date && report.next_due_mileage === null && <Text style={styles.value}>{text.noValue}</Text>}
        </View>
        {renderReportSection({ title: text.warranty, values: [report.warranty_terms], fallback: text.noValue, styles })}
        {renderReportSection({ title: text.validation, values: [report.final_validation], fallback: text.noValue, styles })}
        <Text
          fixed
          style={styles.footer}
          render={({ pageNumber, totalPages }) => `${text.legal} · ${text.page} ${pageNumber}/${totalPages}`}
        />
      </Page>
    </Document>
  )
}

export async function renderDeliveryReportPdfBlob(data: DeliveryReportPdfData) {
  return pdf(deliveryReportDocument(data)).toBlob()
}

export async function downloadDeliveryReportPdf(data: DeliveryReportPdfData) {
  const blob = await renderDeliveryReportPdfBlob(data)
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = `${data.report.report_number}.pdf`
  document.body.appendChild(anchor)
  anchor.click()
  anchor.remove()
  setTimeout(() => URL.revokeObjectURL(url), 2000)
}
