-- Historical migration marker.
--
-- The original 0004 migration mixed local demonstration fixtures with schema
-- history and contained a client_vehicles tuple whose fuel and mileage values
-- were reversed. Production environments that already record this migration
-- must never replay it. Fresh local databases load the corrected, deterministic
-- fixtures from supabase/seed.sql after every schema migration has completed.
--
-- This file intentionally performs no SQL operation. Its filename and migration
-- identifier are retained so repository history remains compatible.
