/**
 * Immutable public configuration used to reproduce documents accepted on
 * 2026-07-02. Do not replace these values with the current legal config.
 */
export const historicalLegalConfig20260702 = {
  appName: 'Clikarage',
  serviceStatement: 'Clikarage est un service édité par RODANBTECH.',
  editorName: 'Anas RODRIGUEZ BENKARROUM',
  tradingName: 'RODANBTECH',
  legalBusinessName: 'Anas RODRIGUEZ BENKARROUM (RODANBTECH)',
  editorLegalStatus: 'Entrepreneur individuel',
  publicationDirector: 'Anas RODRIGUEZ BENKARROUM',
  editorAddress: '47 RUE VIVIENNE, 75002 PARIS, France',
  contactEmail: 'anas.rodriguez@rodanbtech.com',
  privacyContactEmail: 'anas.rodriguez@rodanbtech.com',
  contactPhone: '+33 7 81 18 93 65',
  siren: '103 878 187',
  siret: '103 878 187 00014',
  rneStatus: 'Immatriculé au Registre National des Entreprises (RNE) le 17/04/2026',
  inseeStatus: 'Inscrit à l’Insee le 17/04/2026',
  creationDate: '17/04/2026',
  rcs: 'Non applicable',
  vatNumber: 'Pas de numéro de TVA intracommunautaire valide à ce jour',
  eoriNumber: 'Pas de numéro EORI valide à ce jour',
  activity: 'Programmation informatique',
  nafApeCode: '62.01Z',
  nafApeLabel: 'Programmation informatique',
  naf2025Code: '62.10Y',
  naf2025Label: 'Activités de programmation informatique',
  employees: 'Unité non employeuse',
  domainProviderName: 'Squarespace',
  domainProviderPurpose: 'Gestion du domaine et, le cas échéant, configuration de l’email professionnel',
  emailProviderName: 'Google Workspace / Squarespace, selon la configuration du domaine',
  frontendHostName: 'Vercel Inc.',
  frontendHostAddress: '440 N Barranca Ave #4133, Covina, CA 91723, États-Unis',
  frontendHostWebsite: 'https://vercel.com',
  frontendHostContact: 'Contact légal disponible via https://vercel.com',
  backendProviderName: 'Supabase, Inc.',
  backendProviderWebsite: 'https://supabase.com',
  backendPurpose: 'Base de données, authentification et infrastructure technique',
  backendDataRegion: 'eu-west-3 — West EU (Paris)',
  backendDataRegionPublic: 'Région Supabase du projet pilote : eu-west-3 — West EU (Paris). Les données du projet pilote sont hébergées dans une région européenne Supabase.',
  dpo: 'Aucun délégué à la protection des données désigné à ce stade',
  cnilWebsite: 'https://www.cnil.fr',
  pilotVersion: 'Version pilote',
  lastUpdated: '2026-07-02',
  documentsSensitiveDisabled: true,
  analyticsEnabled: false,
  marketingCookiesEnabled: false,
  commercialOffer: {
    pilotDurationDays: 30,
    paymentEnabledInApp: false,
    onlinePaymentEnabled: false,
    sensitiveDocumentsEnabled: false,
  },
} as const

export const historicalLegalVersions20260702 = {
  terms: '2026-07-02',
  privacy: '2026-07-02',
  pilotAgreement: '2026-07-02',
  dpa: '2026-07-02',
  legalNotice: '2026-07-02',
} as const
